#the port of app
server:
	port:10086
	context-path:

logging:
	level:
	com.joytiger.cihui:DEBUG
	
spring:
	datasource:
		name:joytiger
		url:jdbc:mysql:192.168.1.50:3306/mtJingSai
		username=root
		password=root
		type:com.alibaba.druid.pool.DruidDataSource
		driver-class-name:com.mysql.jdbc.Driver
		filters:stat
		maxActive:20
		initialSize:1
		maxWait:60000
		minIdle:1
		timeBetweenEvictionRunsMillis:60000
		minEvictableIdleTimeMillis:300000
		validationQuery:select 'x'
		testWhileIdle:true
		testOnBorrow:false
		testOnReturn:false
		poolPreparedSatements:true
		maxOpenPreparedStatements:20
mybatis:
	mapperLocations:classpath:classpath:mapper/*.xml	
	typeAliasesPackage:	com.joytiger.cihui.mapper
		